@startuml components

package "ESP32 Microcontroller" {
    [ESP32] 
}

package "Sensors" {
    [Soil_Moisture_Sensor] 
    [Temperature_Sensor] 
    [Waterlevel_Sensor] 
    [Ambient_Light_Sensor]
    [CO2_Sensor]
}

package "Actuators" {
    [Camera]
    [Lights] 
    [Alarm] 
    [Waterpump]
    [Display]
}

package "Peripheral" {
    [WaterTank] 
    [Greenhouse] 
}

ESP32 --> Soil_Moisture_Sensor : Measures soil moisture
ESP32 --> Temperature_Sensor : Measures temperature
ESP32 --> Waterlevel_Sensor : Measures water level in tank
ESP32 --> Ambient_Light_Sensor : Measures ambient light
ESP32 --> Waterpump : Controls water pump
ESP32 --> Lights : Controls lights
ESP32 --> Alarm : Activates alarm
ESP32 --> Camera : Send the Stream to ESP32 Webserver
ESP32 --> CO2_Sensor : Measure CO2

Waterlevel_Sensor --> WaterTank : Monitors water level
Waterpump --> WaterTank : Draws water from tank
Waterpump --> Greenhouse : Waters greenhouse
Lights --> Ambient_Light_Sensor : Adjusts brightness
Alarm --> WaterTank : Alarm for low water level
Camera --> Greenhouse : Stream Greenhouse
CO2_Sensor --> Display : Display CO2
Temperature_Sensor --> Display : Display Temperature
Soil_Moisture_Sensor --> Display : Display Moisture
@enduml